// Static UI strings, indexed by language.
import type { Lang } from "./site.config";

const STRINGS = {
  fr: {
    home: "Accueil",
    callNow: "Appeler",
    callNowFor: "Appelez maintenant",
    getQuote: "Soumission gratuite",
    quickQuote: "Soumission rapide",
    freeInstantQuote: "SOUMISSION GRATUITE",
    enterInfoBelow: "Entrez vos infos ci-dessous",
    services: "Services",
    locations: "Zones",
    serviceArea: "Zone desservie",
    testimonials: "Témoignages",
    about: "À propos",
    contact: "Contact",
    contactUs: "Contactez-nous",
    contactSubtitle: "Réponse rapide. Estimation gratuite.",
    contactHeadline: "Contactez-nous",
    contactPageIntro: "Nous répondons rapidement à toutes les demandes de soumission.",
    aboutTitle: "À propos",
    privacyPolicy: "Politique de confidentialité",
    termsOfUse: "Conditions d'utilisation",
    firstName: "Prénom",
    lastName: "Nom de famille",
    phone: "Téléphone",
    email: "Courriel",
    message: "Message",
    comment: "Commentaire",
    submit: "Envoyer",
    rightsReserved: "Tous droits réservés",
    learnMore: "En savoir plus",
    ourServices: "Nos services à",
    ourServiceAreas: "Nos zones desservies",
    seeAllServices: "Voir tous les services",
    seeAllAreas: "Voir toutes les zones",
    contactByEmail: "Par courriel :",
    quickResponse: "Réponse rapide • Estimation gratuite",
    faq: "Questions fréquentes",
    faqIntro: "Tout ce qu'il faut savoir avant de réserver un débarras.",
  },
  en: {
    home: "Home",
    callNow: "Call",
    callNowFor: "Call now",
    getQuote: "Free quote",
    quickQuote: "Quick quote",
    freeInstantQuote: "FREE INSTANT QUOTE",
    enterInfoBelow: "Enter your info below",
    services: "Services",
    locations: "Locations",
    serviceArea: "Service area",
    testimonials: "Testimonials",
    about: "About",
    contact: "Contact",
    contactUs: "Contact us",
    contactSubtitle: "Fast response. Free estimate.",
    contactHeadline: "Contact us",
    contactPageIntro: "We respond quickly to every quote request.",
    aboutTitle: "About",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    firstName: "First",
    lastName: "Last",
    phone: "Phone",
    email: "Email",
    message: "Message",
    comment: "Comment",
    submit: "Submit",
    rightsReserved: "All rights reserved",
    learnMore: "Learn more",
    ourServices: "Our services in",
    ourServiceAreas: "Our service areas",
    seeAllServices: "See all services",
    seeAllAreas: "See all service areas",
    contactByEmail: "By email:",
    quickResponse: "Fast response • Free estimate",
    faq: "Frequently Asked Questions",
    faqIntro: "Everything you need to know before booking a junk removal.",
  },
} as const;

export function t(lang: Lang) {
  return STRINGS[lang];
}
