// Auto-generated by scripts/generate-site.mjs. Bilingual long-tail FAQ.
// Edit individual entries here once published — re-running the generator
// would overwrite them.

import type { Lang } from "./site.config";

export interface FaqEntry {
  q: string;
  a: string;
}

const FAQ: Record<Lang, FaqEntry[]> = {
  fr: [
    {
      q: `Combien coûte une réfection de toiture à Gatineau ?`,
      a: `Le prix dépend de plusieurs facteurs : superficie du toit, type de matériau (bardeaux d'asphalte vs tôle vs membrane), pente, complexité (cheminées, lucarnes, vallées), et état du pontage. Plutôt que de donner un prix au pied carré qui s'avère rarement exact, nous montons sur votre toit pour une inspection en personne et donnons un prix fixe sur place. Demandez une soumission gratuite par téléphone ou via le formulaire — c'est sans engagement.`,
    },
    {
      q: `Quelle est la durée de vie d'une toiture en bardeaux d'asphalte ?`,
      a: `Une toiture en bardeaux d'asphalte standard à Gatineau dure typiquement 18 à 25 ans, selon la qualité des matériaux, la qualité de l'installation, et la ventilation de l'entretoit. Les bardeaux architecturaux haut de gamme avec une bonne ventilation peuvent atteindre 30 ans. La cause numéro un d'une toiture qui ne dure pas est une mauvaise ventilation — nous la corrigeons par défaut lors de chaque réfection.`,
    },
    {
      q: `Combien de temps prend une réfection complète ?`,
      a: `Une réfection complète sur une maison résidentielle typique à Gatineau prend généralement 2 à 4 jours, selon la superficie, la météo, et la complexité du toit. Nous arrachons toujours l'ancienne toiture jusqu'au pontage, ce qui ajoute du temps mais permet de corriger les problèmes cachés. Une toiture commerciale plate peut prendre une semaine ou plus selon les détails.`,
    },
    {
      q: `Pouvez-vous intervenir en urgence pour une fuite ?`,
      a: `Oui. Pour une fuite active ou un dommage post-tempête, nous intervenons souvent dans les 24 à 48 heures avec une réparation temporaire qui stoppe l'eau. La réparation permanente se fait ensuite quand la météo coopère. Nous comprenons qu'une fuite ne peut pas attendre une semaine — appelez-nous directement pour les urgences plutôt que d'utiliser le formulaire en ligne.`,
    },
    {
      q: `Quelle est la différence entre des bardeaux trois-pattes et architecturaux ?`,
      a: `Les bardeaux trois-pattes (ou bardeaux standards) sont l'option la plus économique avec une durée de vie typique de 15 à 20 ans. Les bardeaux architecturaux (aussi appelés stratifiés ou laminés) sont plus épais, plus lourds, plus résistants au vent, et durent 25 à 30 ans. La différence de prix se rentabilise généralement à long terme — nous expliquons les options en détail lors de la soumission.`,
    },
    {
      q: `Faut-il enlever l'ancienne toiture ou peut-on poser par-dessus ?`,
      a: `Nous arrachons toujours l'ancienne toiture jusqu'au pontage. Poser des bardeaux par-dessus une couche existante est plus rapide pour le couvreur, mais ça réduit la durée de vie de la nouvelle toiture, masque les dommages cachés au pontage, et n'est pas conforme aux normes des manufacturiers (annulation des garanties). C'est non-négociable dans nos installations — vous obtenez le travail bien fait, pas le travail vite fait.`,
    },
    {
      q: `Êtes-vous assurés et accrédités ?`,
      a: `Oui. Notre équipe est entièrement assurée (responsabilité civile et CNESST) et nous travaillons selon les normes de l'Association des maîtres couvreurs du Québec (AMCQ). Nous fournissons sur demande nos certificats d'assurance avant de commencer un projet. C'est non-négociable dans notre secteur — un couvreur sans assurance, c'est votre responsabilité en cas d'accident sur votre propriété.`,
    },
    {
      q: `Offrez-vous des garanties sur le travail ?`,
      a: `Oui. Notre main-d'œuvre est garantie 10 ans pour les réfections complètes, et 2 à 5 ans pour les réparations selon le type. Les matériaux sont couverts par les garanties prolongées des manufacturiers — typiquement 25 à 50 ans pour les bardeaux haut de gamme. Toutes les garanties sont écrites et remises à la fin du projet.`,
    },
    {
      q: `Desservez-vous tout l'Outaouais ?`,
      a: `Oui, nous desservons toute la ville de Gatineau (Hull, Aylmer, Buckingham, Masson-Angers, Pointe-Gatineau, Templeton, Limbour) ainsi que les municipalités environnantes : Cantley, Chelsea, Val-des-Monts et La Pêche. Notre service couvre toute la région de l'Outaouais.`,
    },
    {
      q: `Comment se passe une inspection de toiture ?`,
      a: `Notre couvreur monte sur votre toit pour une inspection visuelle complète : état des bardeaux ou de la membrane, intégrité des solins (cheminées, lucarnes, évents), état des gouttières, ventilation de l'entretoit, et signes d'infiltration. Chaque élément est documenté par photo. Vous recevez un rapport écrit avec recommandations chiffrées : ce qui est conforme, ce qui demande surveillance, ce qui exige une intervention. L'inspection prend environ une heure pour une maison résidentielle typique.`,
    }
  ],
  en: [
    {
      q: `How much does a roof replacement cost in Gatineau?`,
      a: `The price depends on several factors: roof surface area, material type (asphalt shingles vs metal vs membrane), slope, complexity (chimneys, dormers, valleys), and the deck's condition. Rather than quoting a per-square-foot price that's rarely accurate, we get on your roof for an in-person inspection and give a firm price on-site. Request a free quote by phone or via the form — no obligation.`,
    },
    {
      q: `How long does an asphalt-shingle roof last?`,
      a: `A standard asphalt-shingle roof in Gatineau typically lasts 18 to 25 years, depending on material quality, installation quality, and attic ventilation. High-end architectural shingles with good ventilation can reach 30 years. The number-one cause of a roof not lasting is poor ventilation — we fix it by default with every replacement.`,
    },
    {
      q: `How long does a full re-roof take?`,
      a: `A full re-roof on a typical residential home in Gatineau usually takes 2 to 4 days, depending on surface area, weather, and roof complexity. We always tear off the old roof down to the deck, which adds time but lets us correct hidden problems. A flat commercial roof can take a week or more depending on details.`,
    },
    {
      q: `Can you respond to an emergency leak?`,
      a: `Yes. For an active leak or post-storm damage, we often intervene within 24-48 hours with a temporary repair that stops the water. The permanent repair follows once the weather cooperates. We understand a leak can't wait a week — call us directly for emergencies rather than using the online form.`,
    },
    {
      q: `What's the difference between three-tab and architectural shingles?`,
      a: `Three-tab (or standard) shingles are the most economical option with a typical lifespan of 15 to 20 years. Architectural shingles (also called laminated or dimensional) are thicker, heavier, more wind-resistant, and last 25 to 30 years. The price difference usually pays for itself over the long run — we explain the options in detail at quote time.`,
    },
    {
      q: `Should the old roof be removed or can you lay over it?`,
      a: `We always tear the old roof off to the deck. Laying shingles over an existing layer is faster for the roofer but it shortens the new roof's lifespan, hides damage to the deck, and isn't compliant with manufacturer standards (warranties get voided). It's non-negotiable in our installations — you get work done right, not done fast.`,
    },
    {
      q: `Are you insured and accredited?`,
      a: `Yes. Our crew is fully insured (liability + CNESST workers' comp) and we work to the standards of the Association des maîtres couvreurs du Québec (AMCQ). We provide our insurance certificates on request before starting any project. It's non-negotiable in this trade — an uninsured roofer is your liability if anything happens on your property.`,
    },
    {
      q: `Do you offer workmanship warranties?`,
      a: `Yes. Our workmanship is guaranteed 10 years for full replacements, and 2 to 5 years for repairs depending on type. Materials are covered by the manufacturers' extended warranties — typically 25 to 50 years for high-end shingles. All warranties are written and provided at project end.`,
    },
    {
      q: `Do you serve the entire Outaouais region?`,
      a: `Yes, we serve all of Gatineau (Hull, Aylmer, Buckingham, Masson-Angers, Pointe-Gatineau, Templeton, Limbour) plus surrounding municipalities: Cantley, Chelsea, Val-des-Monts, and La Pêche. Our service covers the entire Outaouais region.`,
    },
    {
      q: `How does a roof inspection work?`,
      a: `Our roofer gets on your roof for a complete visual inspection: state of shingles or membrane, flashing integrity (chimneys, dormers, vents), gutter condition, attic ventilation, and signs of infiltration. Every element is documented with photos. You receive a written report with quoted recommendations: what's compliant, what needs monitoring, what requires action. The inspection takes about an hour for a typical residential home.`,
    }
  ],
};

export function getFaq(lang: Lang): FaqEntry[] {
  return FAQ[lang] ?? [];
}
